### ISSUE TITLE
Add negative binomial distribution

### ISSUE THREAD

**Issue by rpglover64** [haskell/statistics#98]
I recently ran into the need. Apparently I'm not the only one:

http://ircbrowse.net/browse/haskell-beginners?id=184140&timestamp=1420085839#t1420085839

>   2015-01-01 <tejon>    Maddeningly, the statistics package on Hackage doesn't do negative binomial. Absolutely everything but, it seems.

**Comment by Shimuuar** [comment]
I don't have to time to add it so I'm marking this as help needed. So pull requests are welcome I guess.

**Comment by szabi** [comment]
Actually, sometime last year I'm pretty sure I expanded my copy of the package with negative binomial, but never created a pull request, as I did not write tests, if I remember correctly. Might look into it.

**Comment by Shimuuar** [comment]
@szabi That would be great!

**Comment by szabi** [comment]
Ok, I looked it up.

Back then I **added** the 
- discrete uniform distribution [finished] and the
- convolution of it (sum of iid discrete uniforms) [might not be finished code, have to check in detail]

and I **looked** into the
- negative binomial.

I did **not** add negative binomial yet, because there is [a huge number of alternative parametrizations](https://en.wikipedia.org/wiki/Negative_binomial_distribution#Alternative_formulations) and no "industry standard" parametrization of the distribution, so I felt a broader discussion would be necessary, which parametrization to use.

**Comment by Shimuuar** [comment]
Could you then create pull request for discrete uniform distribution?

**Comment by szabi** [comment]
It was never finished in a "production quality" sense, so I'll probably have to at least check, maybe even sanitize it somewhat. I'll try to find time and create a pull request, sometime the coming weeks.

Which would be the best place to check out and discuss the <statistics> package user group's preferences wrt. parametrization style for the NBD?

**Comment by Shimuuar** [comment]
There's no hurry.

I think this issue is right place to discuss NBD.

**Comment by aezarebski** [comment]
Hi @szabi is there any interest remaining in adding the negative binomial? 

Regarding the alternative parameterisations, can I put a vote in for the default in R. Even though this uses different parameters from the ones stated on Wikipedia, whatever R has converged on is probably as good a default as you're going to get and then there is a nice reference. Although, this could be a bit problematic if the rest of the distributions don't match up with the R versions.

**Comment by szabi** [comment]
@aezarebski no, sorry, I moved on.
